version: '3.4'
services:
  database:
    # https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-volume:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
  web:
    image: romankrajewski/visense:latest
    ports:
      - "8080:8080"
    volumes:
      - ./sample-data:/sample-data
    depends_on:
      - database
    env_file:
      - database.env #configure db access

  frontend:
    image: romankrajewski/visense-frontend:latest
    ports:
      - "8081:8081"
volumes:
  database-volume:
