version: '3'
services:
  database:
    # https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-volume:/var/lib/postgresql/data/ # persist data even if container shuts down

  web:
    image: romankrajewski/visense:latest
    ports:
      - "8080:8080"
    volumes:
      - ./sample-data:/sample-data
      - frontend-data:/static
    depends_on:
      - database
      - frontend
    env_file:
      - database.env #configure db access
      - webserver_integration.env

  frontend: #only used for copying the public files to the volume so the go server can serve them
    image: romankrajewski/visense-frontend:latest
    volumes:
      - frontend-data:/static

volumes:
  database-volume:
  frontend-data: