version: '3.4'
services:
  watchtower: #service that automatically checks for new docker images. not needed if you run this app locally.
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 #check for updates every 5 min

  web:
    ports:
      - 8080:8080
      - 44344:4443
    env_file:
      - database.env
      - backend.env
    volumes:
      - backend_cert_cache:/certcache

  frontend:
    ports:
      - 80:8080
      - 443:4443
    env_file:
      - frontend.env
    volumes:
      - frontend_cert_cache:/certcache
volumes:
  frontend_cert_cache:
  backend_cert_cache: