on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
name: BuildPush
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
        working-directory: ./app
      - name: BuildPush
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          path: ./app
          repository: romankrajewski/visense
          tags: latest
